//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-add_team_service-SSD_SERVICE_ID_sd_uR32r7vvGH0HEaxs
import { add_team_service as SSD_SERVICE_ID_sd_uR32r7vvGH0HEaxs } from './sd-services/add_team/add_team_service';
//CORE_REFERENCE_IMPORT-add_team_api-SSD_SERVICE_ID_sd_Na84Q8oL14BLH7ce
import { add_team_api as SSD_SERVICE_ID_sd_Na84Q8oL14BLH7ce } from './sd-services/add_team/add_team_api';
//CORE_REFERENCE_IMPORT-get_teams_service-SSD_SERVICE_ID_sd_DTBjhHeQ0o9aZDx7
import { get_teams_service as SSD_SERVICE_ID_sd_DTBjhHeQ0o9aZDx7 } from './sd-services/get_teams/get_teams_service';
//CORE_REFERENCE_IMPORT-get_teams_api-SSD_SERVICE_ID_sd_xr6MmY4qUD8xiMXk
import { get_teams_api as SSD_SERVICE_ID_sd_xr6MmY4qUD8xiMXk } from './sd-services/get_teams/get_teams_api';
//CORE_REFERENCE_IMPORT-get_users_excel-SSD_SERVICE_ID_sd_pPtLqdZddNSuNrMG
import { get_users_excel as SSD_SERVICE_ID_sd_pPtLqdZddNSuNrMG } from './sd-services/get_users/get_users_excel';
//CORE_REFERENCE_IMPORT-update_user_service-SSD_SERVICE_ID_sd_5LzspN9E8sISp90h
import { update_user_service as SSD_SERVICE_ID_sd_5LzspN9E8sISp90h } from './sd-services/patch_user/update_user_service';
//CORE_REFERENCE_IMPORT-update_user-SSD_SERVICE_ID_sd_1s6QZqA2JalJOOVP
import { update_user as SSD_SERVICE_ID_sd_1s6QZqA2JalJOOVP } from './sd-services/patch_user/update_user';
//CORE_REFERENCE_IMPORT-get_user_by_id-SSD_SERVICE_ID_sd_qBmQ5Y4Dvn7IQdDj
import { get_user_by_id as SSD_SERVICE_ID_sd_qBmQ5Y4Dvn7IQdDj } from './sd-services/get_users/get_user_by_id';
//CORE_REFERENCE_IMPORT-get_users_api-SSD_SERVICE_ID_sd_IGNsOOpSteTbHbtV
import { get_users_api as SSD_SERVICE_ID_sd_IGNsOOpSteTbHbtV } from './sd-services/get_users/get_users_api';
//CORE_REFERENCE_IMPORT-barcode_generate-SSD_SERVICE_ID_sd_x67Ixlrl8PZJfOB3
import { barcode_generate as SSD_SERVICE_ID_sd_x67Ixlrl8PZJfOB3 } from './sd-services/user registration/barcode_generate';
//CORE_REFERENCE_IMPORT-user_registration_service-SSD_SERVICE_ID_sd_JoNOAtsI08gNdk19
import { user_registration_service as SSD_SERVICE_ID_sd_JoNOAtsI08gNdk19 } from './sd-services/user registration/user_registration_service';
//CORE_REFERENCE_IMPORT-user_registration_api-SSD_SERVICE_ID_sd_71EcxVPTkPTzMzQG
import { user_registration_api as SSD_SERVICE_ID_sd_71EcxVPTkPTzMzQG } from './sd-services/user registration/user_registration_api';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-add_team_service-SSD_SERVICE_ID_sd_uR32r7vvGH0HEaxs
SSD_SERVICE_ID_sd_uR32r7vvGH0HEaxs,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-add_team_api-SSD_SERVICE_ID_sd_Na84Q8oL14BLH7ce
SSD_SERVICE_ID_sd_Na84Q8oL14BLH7ce,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_teams_service-SSD_SERVICE_ID_sd_DTBjhHeQ0o9aZDx7
SSD_SERVICE_ID_sd_DTBjhHeQ0o9aZDx7,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_teams_api-SSD_SERVICE_ID_sd_xr6MmY4qUD8xiMXk
SSD_SERVICE_ID_sd_xr6MmY4qUD8xiMXk,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_users_excel-SSD_SERVICE_ID_sd_pPtLqdZddNSuNrMG
SSD_SERVICE_ID_sd_pPtLqdZddNSuNrMG,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_user_service-SSD_SERVICE_ID_sd_5LzspN9E8sISp90h
SSD_SERVICE_ID_sd_5LzspN9E8sISp90h,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-update_user-SSD_SERVICE_ID_sd_1s6QZqA2JalJOOVP
SSD_SERVICE_ID_sd_1s6QZqA2JalJOOVP,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_user_by_id-SSD_SERVICE_ID_sd_qBmQ5Y4Dvn7IQdDj
SSD_SERVICE_ID_sd_qBmQ5Y4Dvn7IQdDj,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-get_users_api-SSD_SERVICE_ID_sd_IGNsOOpSteTbHbtV
SSD_SERVICE_ID_sd_IGNsOOpSteTbHbtV,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-barcode_generate-SSD_SERVICE_ID_sd_x67Ixlrl8PZJfOB3
SSD_SERVICE_ID_sd_x67Ixlrl8PZJfOB3,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-user_registration_service-SSD_SERVICE_ID_sd_JoNOAtsI08gNdk19
SSD_SERVICE_ID_sd_JoNOAtsI08gNdk19,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-user_registration_api-SSD_SERVICE_ID_sd_71EcxVPTkPTzMzQG
SSD_SERVICE_ID_sd_71EcxVPTkPTzMzQG,
];
